// ***************************************************************************************
// Copyright (c) 2023-2025 Peng Cheng Laboratory
// Copyright (c) 2023-2025 Institute of Computing Technology, Chinese Academy of Sciences
// Copyright (c) 2023-2025 Beijing Institute of Open Source Chip
//
// iEDA is licensed under Mulan PSL v2.
// You can use this software according to the terms and conditions of the Mulan PSL v2.
// You may obtain a copy of Mulan PSL v2 at:
// http://license.coscl.org.cn/MulanPSL2
//
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
// EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
// MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
//
// See the Mulan PSL v2 for more details.
// ***************************************************************************************
/* Generated by Cython 0.29.33 */

#ifndef __PYX_HAVE__PyModel
#define __PYX_HAVE__PyModel

#include "Python.h"
#include "pgl.h"

#ifndef __PYX_HAVE_API__PyModel

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C PyObject *pyLoadModel(std::string const &);
__PYX_EXTERN_C PyObject *pyLinearModel(std::vector<std::vector<double> >  const &, std::vector<double>  const &);
__PYX_EXTERN_C PyObject *pyCatBoostModel(std::vector<std::vector<double> >  const &, std::vector<double>  const &);
__PYX_EXTERN_C PyObject *pyXGBoostModel(std::vector<std::vector<double> >  const &, std::vector<double>  const &);
__PYX_EXTERN_C double pyPredict(std::vector<double>  const &, PyObject *);
__PYX_EXTERN_C PyObject *pyGenAX(void);
__PYX_EXTERN_C void pySaveFig(PyObject *, std::string const &);
__PYX_EXTERN_C void pyPlotPoint(PyObject *, icts::CtsPoint<double>  const &, std::string const &);
__PYX_EXTERN_C void pyPlotSegment(PyObject *, icts::CtsSegment<double>  const &, std::string const &);
__PYX_EXTERN_C void pyPlotPolygon(PyObject *, icts::CtsPolygon<double>  const &, std::string const &);
__PYX_EXTERN_C void pyPlot(PyObject *, std::vector<double>  const , std::vector<double>  const , std::string const &);

#endif /* !__PYX_HAVE_API__PyModel */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initPyModel(void);
#else
PyMODINIT_FUNC PyInit_PyModel(void);
#endif

#endif /* !__PYX_HAVE__PyModel */
