// ***************************************************************************************
// Copyright (c) 2023-2025 Peng Cheng Laboratory
// Copyright (c) 2023-2025 Institute of Computing Technology, Chinese Academy of Sciences
// Copyright (c) 2023-2025 Beijing Institute of Open Source Chip
//
// iEDA is licensed under Mulan PSL v2.
// You can use this software according to the terms and conditions of the Mulan PSL v2.
// You may obtain a copy of Mulan PSL v2 at:
// http://license.coscl.org.cn/MulanPSL2
//
// THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
// EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
// MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
//
// See the Mulan PSL v2 for more details.
// ***************************************************************************************
#include "idrc_violation.h"

#include "DRCViolationType.h"

namespace idrc {

/**
 * check if violation is legal,
 * true : legal, ignored this violation
 * false : illegal, need to save this violation
 */
bool DrcViolation::ignored()
{
  if (_violation_type == ViolationEnumType::kDefaultSpacing || _violation_type == ViolationEnumType::kPRLSpacing) {
    for (auto net_id : _net_ids) {
      if (net_id >= 0 || net_id == NET_ID_PDN || net_id == NET_ID_VDD || net_id == NET_ID_VSS) {
        return false;  /// need to save
      }
    }

    return true;  /// environment violation, maybe generated by foundry, ignore this violation
  }

  return false;
}

}  // namespace idrc